- name: fetch save
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../ansible_vars.yml

  tasks:
    - digital_ocean_droplet:
        unique_name: yes # "yes" makes it idempotent
        region: tor1 # slug of the region you would like your server to be created in.
        image: ubuntu-18-04-x64 # slug of the image you would like the droplet created with.
        wait: yes
        name: "factorio-srv" # name of the droplet
        size_id: s-2vcpu-4gb # slug of the size you would like the droplet created with.
        monitoring: yes
        state: present
        ssh_keys: "{{ do_ssh_keys }}" 
      register: created_droplet

    - debug:
        msg: "server ID is {{ created_droplet.data.droplet.id }}"
    
    - debug:
        msg: "server IP is {{ created_droplet.data.ip_address }}"

    - name: add hosts
      add_host:
        name: "{{ created_droplet.data.ip_address }}"
        groups: "digitalocean"

- name: get the save file
  hosts: digitalocean
  user: root
  gather_facts: true # this needs to be true here so we can populate the ansible date / time variables

  tasks:
    - name: stop the factorio service, if started # the server automatically saves the game when it's stopped gracefully like this
      service:
        name: factorio
        state: stopped

    - name: fetch the save file
      fetch:
        src: /opt/factorio/saves/latest_save.zip
        dest: ../factorio_saves/save_{{ ansible_date_time.date }}_{{ ansible_date_time.epoch }}.zip
        flat: yes # overrides default behavior of saving/by/the/whole/path

    - name: restart the factorio service
      service:
        name: factorio
        state: stopped